FROM openjdk:11

LABEL description "Lambda Java worker."
LABEL version "1.0.0"
LABEL maintainer "Danilo Peixoto"

WORKDIR /usr/bin/java_worker/

#COPY build/java_worker.jar .

#CMD ["java", "-jar", "-Dspring.profiles.active=production", "java_worker.jar"]
